# Generated by Django 6.0.6 on 2026-06-22 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroLoteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Numero de Loteria')),
                ('propietario', models.CharField(max_length=150, verbose_name='Nombre del Propietario')),
                ('fecha', models.DateField(verbose_name='Fecha del Sorteo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('ganador', 'Ganador'), ('no_ganador', 'No ganador')], default='activo', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Numero de Loteria',
                'verbose_name_plural': 'Numeros de Loteria',
                'unique_together': {('numero', 'fecha')},
            },
        ),
    ]
