# Generated by Django 6.0.6 on 2026-06-22 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numeroloteria',
            name='estado',
        ),
    ]
